In [1]:
from utils import lire_alpha_digit
import principal_DBN_alpha as DBN
import principal_DNN_MNIST as DNN
import numpy as np
import matplotlib.pyplot as plt

import utils

In [2]:
X_train = lire_alpha_digit('3')
p = X_train.shape[1]
num_layers=3
neurons = [(p, p // 2), (p // 2, p // 4), (p // 4, p // 6)]

assert num_layers == len(neurons)

dnn = DBN.init_DNN(num_layers, neurons)


Download completed, data available in /data/binaryalphadigs.mat
[[0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 0 0]
 [0 1 1 ... 1 1 1]]


In [3]:
sortie = DNN.entree_sortie_reseau(dnn, X_train)

In [4]:
X_train, X_test, y_train, y_test = utils.fetch_mnist_digits_data(60000)